# Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/

# https://docs.docker.com/compose/compose-file/

version: "3.6"

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.gunicorn
    restart: unless-stopped
    environment:
     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
     - SECRET_KEY=${SECRET_KEY}
# https://docs.gunicorn.org/en/stable/settings.html
# https://pythonspeed.com/articles/gunicorn-in-docker/
    command: gunicorn -c gunicorn.config.py wsgi:app
# using "ports" makes flask/gunicorn accessible without going through nginx
    expose:
      - 5000
#    ports:
#     - "5000:5000"
    volumes:
     - ${PWD}/:/scratch
     - ${PWD}/flask/logs:/home/appuser/app/logs/
     - ${PWD}/flask/users_sqlite.db:/home/appuser/app/users_sqlite.db
     - ${PWD}/flask/data.json:/home/appuser/app/data.json
     - /var/log/auth.log:/home/appuser/app/logs/auth.log
  nginx:
    build: ./services/nginx
    ports:
     - "80:80"
     - "443:443"
#      - 1337:80
    volumes:
    - ${PWD}/flask/logs/:/logs/
    - ${PWD}/certs/:/certs/
    depends_on:
      - flask

