# https://docs.docker.com/compose/compose-file/

version: "3.7"

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.gunicorn
# https://docs.gunicorn.org/en/stable/settings.html
    command: >
      gunicorn
      --bind 0.0.0.0:5000
      --log-level debug
      wsgi:app
      --capture-output 
      --access-logfile=-
      --error-logfile=-
#      --enable-stdio-inheritance
# using "ports" makes flask/gunicorn accessible without going through nginx
    expose:
      - 5000
#    ports:
#     - "5000:5000"
    volumes:
#     - .:/scratch
     - ${PWD}/flask/data.json:/home/appuser/app/data.json
    depends_on:
     - mathjax

#  db:
#    image: redis
#    expose:
#     - 6379
#    ports:
#     - "6379:6379"

  nginx:
    build: ./services/nginx
    ports:
     - "80:80"
#      - 1337:80
    depends_on:
      - flask

#  mathjax:
#    build: ./services/mathjax
#    ports:
#     - "5009:5009"
