inference_rules_db_path: 'DataSource/CSVS/inference_rules_database.csv'
inference_rules_ast_path: 'v4_file_per_expression/inference_rules/*.ast'
expressions_tex_path: 'v4_file_per_expression/expressions/*.tex'
tex_feeds_path: 'v4_file_per_expression/feeds/*.tex'
expression_derivations_path: 'v4_file_per_expression/derivations/*'
