# QUICK START:
docker build -t flask_ub .; docker run -it --rm -v`pwd`/data.json:/home/appuser/app/data.json -v`pwd`/logs/:/home/appuser/app/logs/ --publish 5000:5000 flask_ub

# MANUAL start
docker build -t flask_ub .; docker run -it --rm -v`pwd`:/scratch -v`pwd`/data.json:/home/appuser/app/data.json -v`pwd`/logs/:/home/appuser/app/logs/ --entrypoint='' --publish 5000:5000 flask_ub /bin/bash





# Build the image
docker build -t flask_ub .

# run container in detached mode
docker run -d -p 5000:5000 flask_ub

# run container interactively
docker run -it flask-ub /bin/bash
# Since I have a defined entrypoint, I use
docker run -it --entrypoint /bin/bash flask_ub
# with a mount
docker run -it --mount type=bind,source="$(pwd)",target=/another  --entrypoint /bin/bash flask_ub
# with ports exposed
docker run -it --publish 5000:5000 --mount type=bind,source="$(pwd)",target=/another  --entrypoint /bin/bash flask_ub


# list all containers
docker ps -a


docker stop [YOUR CONTAINER NUMBER HERE]


To use Docker Compose,
docker-compose up


https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
