# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(max_length=800),
        ),
    ]
