
# Build the image
docker build -t flask-ub:latest .

# run container in detached mode
docker run -d -p 5000:5000 flask-ub

# run container interactively
docker run -it flask-ub /bin/bash
# Since I have a defined entrypoint, I use
docker run -it --entrypoint /bin/bash flask_ub

# list all containers
docker ps -a


docker stop [YOUR CONTAINER NUMBER HERE]


To use Docker Compose,
docker-compose up


https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
