# Ben Payne
# Physics Derivation Graph
# https://allofphysics.com

# Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/

# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/compose-file/#environment
version: "3.6"

services:
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    restart: unless-stopped
# using "ports" makes flask/gunicorn accessible without going through nginx
    environment:
     - SECRET_KEY=${SECRET_KEY}
    expose:
      - 5000
    depends_on:
      neo4j_docker:
# https://docs.docker.com/compose/compose-file/05-services/#healthcheck
        condition: service_healthy
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
     - "5000:5000"
    volumes:
     - ${PWD}/:/scratch
     - './dumping_grounds:/code/static/dumping_grounds'


  # see https://neo4j.com/docs/operations-manual/current/docker/introduction/
  # https://neo4j.com/docs/operations-manual/current/docker/clustering/
  # https://stackoverflow.com/questions/48465046/run-neo4j-with-docker-compose-neo4j-not-accessible-from-localhost7474
  # https://medium.com/@faaizhussain/neo4j-4-0-docker-compose-9bead6634c8
  neo4j_docker:
    image: neo4j:4.4.4-community
    restart: unless-stopped

    hostname: neo4j_host

    #network_mode: "bridge"
    # https://stackoverflow.com/a/48637671/1164295
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network


    # The ports that will be accessible from outside the container
    # 7474=HTTP, 7473=HTTPS, 7687=Bolt; as per https://neo4j.com/developer/docker-run-neo4j/
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    # as per https://neo4j.com/docs/operations-manual/current/docker/clustering/
    volumes:
      - './neo4j_pdg/data:/var/lib/neo4j/data'
      - './neo4j_pdg/logs:/var/lib/neo4j/logs'
      - './neo4j_pdg/conf:/var/lib/neo4j/conf'
      - './neo4j_pdg/plugins:/var/lib/neo4j/plugins'
      - './dumping_grounds:/var/lib/neo4j/dumping_grounds'
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
    # see https://neo4j.com/docs/operations-manual/current/docker/ref-settings/
    # https://community.neo4j.com/t/docker-compose-setting-for-apoc-installation/11621/9
    # https://linuxtut.com/en/a37f1ee0e486658d10de/
    # https://neo4j.com/labs/apoc/4.1/installation/
    environment:
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_directories_import=dumping_grounds # relative to /var/lib/neo4j
      - NEO4J_dbms_security_procedures_allowlist=gds.*, apoc.*
#      - NEO4JLABS_PLUGINS=["apoc"] # downloads from gitlab everytime the container is started
    # https://stackoverflow.com/a/74689805/1164295
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 3s
      timeout: 10s
      retries: 20
      start_period: 3s

networks:
  neo4j-internal:
    driver: bridge

# EOF
